export const POPULAR_SERVICES = [
    { id: 'netflix', name: 'Netflix', logoKey: 'netflix' },
    { id: 'spotify', name: 'Spotify', logoKey: 'spotify' },
    { id: 'youtube', name: 'YouTube', logoKey: 'youtube' },
    { id: 'amazon-prime', name: 'Amazon Prime', logoKey: 'amazon-prime' },
    { id: 'disney-plus', name: 'Disney+', logoKey: 'disney-plus' },
    { id: 'icloud', name: 'iCloud', logoKey: 'icloud' },
    { id: 'blutv', name: 'BluTV', logoKey: 'blutv' },
    { id: 'exxen', name: 'Exxen', logoKey: 'exxen' },
    { id: 'bein-sports', name: 'beIN Sports', logoKey: 'bein-sports' },
    { id: 'ssport', name: 'S Sport', logoKey: 'ssport' },
    { id: 'adobe-creative-cloud', name: 'Adobe CC', logoKey: 'adobe-creative-cloud' },
    { id: 'canva', name: 'Canva', logoKey: 'canva' },
    { id: 'chatgpt', name: 'ChatGPT', logoKey: 'chatgpt' },
    { id: 'gemini', name: 'Gemini', logoKey: 'gemini' },
    { id: 'onedrive', name: 'OneDrive', logoKey: 'onedrive' },
    { id: 'trendyol', name: 'Trendyol Plus', logoKey: 'trendyol' },
    { id: 'hepsiburada', name: 'Hepsiburada Premium', logoKey: 'hepsiburada' },
    { id: 'x', name: 'X', logoKey: 'x' },
];
